// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

type Invite struct {
	ID     int64
	Code   string
	Used   int64
	UserID int64
}

type Service struct {
	ID           int64
	Name         string
	Type         string
	CreatedAt    int64
	ExpiresAt    int64
	Prolong      int64
	ProlongPrice int64
	UserID       int64
	LocationID   int64
}

type ServiceLocation struct {
	ID       int64
	Name     string
	Address  string
	Services string
}

type ServicePrice struct {
	Amount int64
	Type   string
}

type Transaction struct {
	ID        int64
	PaymentID string
	Amount    int64
	Status    string
	Timestamp int64
	Url       string
	UserID    int64
}

type User struct {
	ID           int64
	Name         string
	PasswordHash string
	Balance      int64
	Invites      int64
}
